name: Append build number to version

inputs:
  package:
    description: Package name
    required: true

runs:
  using: composite
  steps:
    - name: Print old version number
      env:
        VERSION_FILE: ${{ inputs.package }}/__init__.py
        VERSION_REGEX: ^__version__ = \"\(.*\)\" *$
      run: |
        echo -e "Hello"
        OLD_VERSION=$(sed -n "s/${VERSION_REGEX}/\1/p" "${VERSION_FILE}")
        echo "::set-env name=GIGGLE::$OLD_VERSION
        echo -e "old-version $(echo $OLD_VERSION)"
        echo -e "GIGGLE $(echo $GIGGLE)"
      shell: bash
    - name: Append build number to version
      env:
        VERSION_FILE: ${{ inputs.package }}/__init__.py
        VERSION_REGEX: ^__version__ = \"\(.*\)\" *$
        NEW_VERSION: __version__ = \"\1.dev${{ github.run_number }}\"
      run: sed -i "s/${VERSION_REGEX}/${NEW_VERSION}/" "${VERSION_FILE}"
      shell: bash
    - name: Print new version number
      env:
        VERSION_FILE: ${{ inputs.package }}/__init__.py
        VERSION_REGEX: ^__version__ = \"\(.*\)\" *$
      run: |
        echo -e "Goodbye"
        NEW_VERSION=$(sed -n "s/${VERSION_REGEX}/\1/p" "${VERSION_FILE}")
        echo -e "new-version $(echo $NEW_VERSION)"
      shell: bash
