name: Append build number to version

inputs:
  package:
    description: Package name
    required: true

runs:
  using: composite
  steps:
    - name: Print old version number
      env:
        VERSION_FILE: ${{ inputs.package }}/__init__.py
        VERSION_REGEX: ^__version__ = \"\(.*\)\" *\r
      run: |
        NEW_VERSION=$(sed -n "s/${VERSION_REGEX}/\1/p" "${VERSION_FILE}")
        echo "::debug name=old-version::${NEW_VERSION}"
      shell: bash
    - name: Append build number to version
      env:
        VERSION_FILE: ${{ inputs.package }}/__init__.py
        OLD_VERSION: ^*__version__ *= *\"\([0-9]\+.[0-9]\+.[0-9]\+\)\" *$
        NEW_VERSION: __version__ = \"\1.dev${{ github.run_number }}\"
      run: sed -i "s/${OLD_VERSION}/${NEW_VERSION}/" "${VERSION_FILE}"
      shell: bash
    - name: Print new version number
      env:
        VERSION_FILE: ${{ inputs.package }}/__init__.py
        VERSION_REGEX: ^__version__ = \"\(.*\)\" *\r
      run: |
        OLD_VERSION=$(sed -n "s/${VERSION_REGEX}/\1/p" "${VERSION_FILE}")
        echo "::debug name=new-version::${OLD_VERSION}"
      shell: bash
