name: Append build number to version

inputs:
  package:
    description: Package name
    required: true

runs:
  using: composite
  steps:
    - name: Get old version number
      env:
        VERSION_FILE: ${{ inputs.package }}/__init__.py
        VERSION_REGEX: ^__version__ = \"\(.*\)\" *$
      run: |
        OLD_VERSION=$(sed -n "s/${VERSION_REGEX}/\1/p" "${VERSION_FILE}")
        echo -e "old-version=$OLD_VERSION" >> $GITHUB_ENV
      shell: bash
    - name: Print new version number
      run: |
        NEW_VERSION=${{ env.old-version }}.dev${{ github.run_number }}
        echo -e "new-version=$NEW_VERSION" >> $GITHUB_ENV
    - name: Print version numbers
      run: |
        echo -e "Old Version: ${{ env.old-version }}"
        echo -e "New Version: ${{ env.new-version }}"
      shell: bash
    - name: Append build number to version
      env:
        VERSION_FILE: ${{ inputs.package }}/__init__.py
        OLD_VERSION_LINE: ^__version__ *= *\"${{ env.old-version }}\" *$
        NEW_VERSION_LINE: __version__ = \"${{ env.new-version }}\"
      run: sed -i "s/${OLD_VERSION_LINE}/${NEW_VERSION_LINE}/" "${VERSION_FILE}"
      shell: bash
