name: Publish to TestPyPI

on: push

jobs:
  build-and-publish:
    name: Build and publish distributions to TestPyPi
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout source
      uses: actions/checkout@master

    - name: Append commit hash to version number
      run: |
        VERSION_FILE="nygame/__init__.py"
        OLD_VERSION="^ *__version__ *= *\"\([0-9]\+.[0-9]\+.[0-9]\+\)\" *$"
        NEW_VERSION="__version__ = \\\"\1.dev${GITHUB_RUN_NUMBER}\\\""
        sed -i "s/${OLD_VERSION}/${NEW_VERSION}/" "$VERSION_FILE"

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install build dependencies
      run: python -m pip install build --user

    - name: Build distributions
      run: python -m build --sdist --wheel --outdir dist/ .

    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
